# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08tc.proto\x12\x03rpc\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"?\n\x0b\x41ttestation\x12\r\n\x05quote\x18\x01 \x01(\t\x12\x12\n\nmr_enclave\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x19\n\x06Status\x12\x0f\n\x07version\x18\x01 \x01(\t\"@\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\r\n\x05nonce\x18\x04 \x01(\x04\"3\n\x08Response\x12\x12\n\nerror_code\x18\x01 \x01(\r\x12\x13\n\x0bresponse_tx\x18\x02 \x01(\x0c\"\x07\n\x05\x45mpty2\xf0\x01\n\ttowncrier\x12(\n\x06\x61ttest\x12\n.rpc.Empty\x1a\x10.rpc.Attestation\"\x00\x12#\n\x06status\x12\n.rpc.Empty\x1a\x0b.rpc.Status\"\x00\x12(\n\x07process\x12\x0c.rpc.Request\x1a\r.rpc.Response\"\x00\x12&\n\x0bparticipate\x12\t.rpc.Data\x1a\n.rpc.Empty\"\x00\x12 \n\x06id_nft\x12\t.rpc.Data\x1a\t.rpc.Data\"\x00\x12 \n\x06raffle\x12\t.rpc.Data\x1a\t.rpc.Data\"\x00\x62\x06proto3')



_DATA = DESCRIPTOR.message_types_by_name['Data']
_ATTESTATION = DESCRIPTOR.message_types_by_name['Attestation']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'tc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.Data)
  })
_sym_db.RegisterMessage(Data)

Attestation = _reflection.GeneratedProtocolMessageType('Attestation', (_message.Message,), {
  'DESCRIPTOR' : _ATTESTATION,
  '__module__' : 'tc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.Attestation)
  })
_sym_db.RegisterMessage(Attestation)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'tc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.Status)
  })
_sym_db.RegisterMessage(Status)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'tc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'tc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.Response)
  })
_sym_db.RegisterMessage(Response)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'tc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

_TOWNCRIER = DESCRIPTOR.services_by_name['towncrier']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATA._serialized_start=17
  _DATA._serialized_end=37
  _ATTESTATION._serialized_start=39
  _ATTESTATION._serialized_end=102
  _STATUS._serialized_start=104
  _STATUS._serialized_end=129
  _REQUEST._serialized_start=131
  _REQUEST._serialized_end=195
  _RESPONSE._serialized_start=197
  _RESPONSE._serialized_end=248
  _EMPTY._serialized_start=250
  _EMPTY._serialized_end=257
  _TOWNCRIER._serialized_start=260
  _TOWNCRIER._serialized_end=500
# @@protoc_insertion_point(module_scope)
